//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentCommands.MobileApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentCommands.MobileApp.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following 4 buttons are tied together through a fluent command manager. Each button is registered to an own execution group with different locking behaviors. These are the configurations from left to right: LockAll, LockOthers, LockThis and LockNothing. Press on each button to see how they interact with the other buttons. A green button indicates that the command of the button can execute. A red button indicates that the command can currently not execute..
        /// </summary>
        internal static string Example1Description {
            get {
                return ResourceManager.GetString("Example1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 1.
        /// </summary>
        internal static string Example1Headline {
            get {
                return ResourceManager.GetString("Example1Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a usecase..
        /// </summary>
        internal static string Example2Description {
            get {
                return ResourceManager.GetString("Example2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 2.
        /// </summary>
        internal static string Example2Headline {
            get {
                return ResourceManager.GetString("Example2Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an implementation of the command pattern.. The fluent command is pure asynchronous command..
        /// </summary>
        internal static string InfoDescription {
            get {
                return ResourceManager.GetString("InfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is FluentCommands?.
        /// </summary>
        internal static string InfoHeadline {
            get {
                return ResourceManager.GetString("InfoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to see some more coding examples you can visit the repository. The library can be found on Nuget with the name FluentCommandsNet..
        /// </summary>
        internal static string MoreInfoDescription {
            get {
                return ResourceManager.GetString("MoreInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where can I read more about it?.
        /// </summary>
        internal static string MoreInfoHeadline {
            get {
                return ResourceManager.GetString("MoreInfoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Repository.
        /// </summary>
        internal static string OpenRepositoryText {
            get {
                return ResourceManager.GetString("OpenRepositoryText", resourceCulture);
            }
        }
    }
}
